"""
Heart of the LangGraph portion of this application

Any information passed between the nodes (like the search queries, 
retrieved text, or loop counter) must be defined here
"""

from typing import Any, Dict, List, TypedDict

# Central state object for shared memory of routing engine
class GraphState(TypedDict):
    # The original, unmodified question asked by the user
    question: str
    # The current query being sent to pinecone
    current_query: str
    # History of rewritten queries (prevents duplicate searches)
    query_history: List[str]
    # Relevant text chunks that passed the grading
    documents: List[Dict[str, Any]]
    # Loop counter to ensure no infinite cycles
    loop_step: int
    # The final response generated by the LLM after processing the retrieved documents
    final_response: str
    # Tracking fields
    node_telemetry: List[Dict[str, Any]]
    # Flag indicating whether the overall operation was successful
    is_successful: bool